### ISSUE TITLE
Update to angular v13

### ISSUE THREAD

**Issue by djkris105** [diz517/ngx-line-truncation#58]
Is it possible to get the upgrade the dependencies to angular v13?

**Comment by rickynguyen4590** [comment]
We could create PR if you need?

**Comment by diz517** [comment]
👋 hey, I'm sorry that i haven't been doing the basic maintenance, would be great if you can, but if you don't do till June2022, i will do it. thank you very much! 

Di

**Comment by rickynguyen4590** [comment]
@diz517, PR has been created. Could you check this [PR](https://github.com/diz517/ngx-line-truncation/pull/68)

**Comment by diz517** [comment]
V1.8.1 published https://www.npmjs.com/package/ngx-line-truncation
tested with https://github.com/diz517/ngx-line-truncation-demo

for `v1.8.1` and above, will support angular 13 project (you won't get peer dependency error when npm i)
